name: Generate Cookbook PDF

on:
  push:
    branches:
      - master

jobs:
  build-cookbook:
    runs-on: ubuntu-latest

    container:
      image: pandoc/latex:2.19
      options: --user root

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set working directory (explicit)
      run: cd $GITHUB_WORKSPACE

    - name: Make script executable
      run: chmod +x ./generate-pdf.sh

    - name: Run cookbook builder
      run: ./generate-pdf.sh

    - name: Upload PDF
      uses: actions/upload-artifact@v4
      with:
        name: cookbook
        path: cookbook.pdf

    - name: Commit cookbook.pdf to repo
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add cookbook.pdf
        git commit -m "[skip actions] Update cookbook.pdf"
        git push