name: Update table of contents

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        python-version: [3.8]

    steps:
      - name: Run updater
        run: |
          git config user.name github-actions
          git config user.email github-actions@domain.invalid
          python update.py
          git commit -am "[skip actions] auto-update table of contents"
          git push origin HEAD
